global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nestjs'
    static_configs:
      - targets: ['localhost:5000']  # Use your NestJS app's actual port
        labels:
          application: 'nestjs-app'