name: CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm run test

      # - name: Create .env file
      #   run: |
      #     echo "POSTGRESQL_HOST=${{ secrets.HOST }}" >> .env
      #     echo "POSTGRESQL_DBPORT=${{ secrets.DBPORT }}" >> .env
      #     echo "POSTGRESQL_DB_USERNAME=${{ secrets.GOOGLE_REDIDB_USERNAMERECT_URL }}" >> .env
      #     echo "POSTGRESQL_DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
      #     echo "POSTGRESQL_DATABASE=${{ secrets.DATABASE }}" >> .env
      #     echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Deploy to Server 
        uses: appleboy/ssh-action@master
        with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Install Node.js
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
      
          # Verify Node.js installation
          node -v
          npm -v
      
          # Install PM2 globally
          sudo npm install -g pm2
      
          # Clone the repository if it doesn't exist, otherwise pull the latest changes
          if [ ! -d "/home/ubuntu/Stinger-service" ]; then
            git clone https://github.com/akhiljith77/Stinger-service.git /home/ubuntu/Stinger-service
          else
            cd /home/ubuntu/Stinger-service
            git pull origin master
          fi
      
          # Build and start the application
          cd /home/ubuntu/Stinger-service
          npm install
          npm run build
          pm2 restart Stinger-service || pm2 start dist/main.js --name "Stinger-service"     
